# Generated by Django 5.1.5 on 2025-02-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='address',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='emp_id',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='name',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=10),
        ),
        migrations.AddField(
            model_name='emp',
            name='working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
    ]
